name: TeX Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          cd path/to/latex/directory
          tlmgr install bibtex8
          make

      - name: Upload PDF file
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: path/to/latex/directory/main.pdf
